export const SET_KEYWORD = "SET_KEYWORD";

export const FETCH_IMAGES_START = "FETCH_IMAGES_START";
export const FETCH_IMAGES_SUCCESS = "FETCH_IMAGES_SUCCESS";
export const FETCH_IMAGES_FAIL = "FETCH_IMAGES_FAIL";

export const SAVE_QUERY = "SAVE_QUERY";

export const PRESS_SAVED_QUERY = "PRESS_SAVED_QUERY";
export const SHOW_SAVED_QUERY_RESULT = "SHOW_SAVED_QUERY_RESULT";

export const LEAVE_ERROR_MESSAGE = "LEAVE_ERROR_MESSAGE";
